### PR TITLE
[WIP] macOS support and C11 pthread wrapper

### PR DESCRIPTION
**Pull request by pankkor**
Hi, in the process of porting the code to macOS I encountered a problem with C11 threads.

Clang on macOS (and afaik MSVC on Windows) doesn't have support for C11 threads.
I wrote a tiny wrapper around pthreads for few C11 functions that are used in the code.

I wonder if this approach looks good to you?

The code is barely tested.

### CODE REVIEW

**Comment by pankkor** [comment]
I've added Windows support as well. Now I need to test everything. Still waiting for your response if the approach looks viable to you.

P.S. I'm not familiar with Draft PR requests here on github. Perhaps you don't see notifications until I explicitly mention you. For that case cc @graphitemaster. I apologize in advance if that spams you.

**Comment by graphitemaster** [comment]
Closing, should be addressed by now in thread.{h,c}

**Comment by pankkor** [comment]
General question: considering I’m willing to contribute my time to this project, do you need any help?

**Comment by graphitemaster** [comment]
> General question: considering I’m willing to contribute my time to this project, do you need any help?

Absolutely. The more help the merrier. The threads stuff I was already working on prior to this PR, that's the only reason for not accepting it. I needed to address issues on Windows and also to make it compile as C++ since MSVC.

We have a channel on the official Odin Discord server if you'd like to communicate on what to work on.

**Pull request closed without merging**
